### ISSUE TITLE
Unable to share link from YouTube

### ISSUE THREAD

**Issue by Hooleymass** [animegamer4422/MY-MUSIC#2]
/data/data/com.termux/files/home/bin/termux-url-opener: 71: Syntax error: "(" unexpected (expecting ";;")

[Process completed (code 2) - press Enter]

**Comment by Hari-Pi** [comment]
Sorry I was busy with my daily life , so couldn't respond earlier

**Comment by Hari-Pi** [comment]
> /data/data/com.termux/files/home/bin/termux-url-opener: 71: Syntax error: "(" unexpected (expecting ";;")
> 
> [Process completed (code 2) - press Enter]

The latest commit fixes the issue
I hope you have a good day

**Comment by Hari-Pi** [comment]
Just a reminder that I've fixed all the earlier issues and updated the script appropriately do give it a try and let me know if anything bothers you, 
I hope you have a great day

**Comment by Hooleymass** [comment]
Thanks man you have been of great help

**Comment by Hari-Pi** [comment]
No problem , ping me in case you need any help
